default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: '2156'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_medium_clone_development

test:
  <<: *default
  database: my_medium_clone_test

production:
  <<: *default
  database: my_medium_clone_production
  username: my_medium_clone
  password: <%= ENV['MY_MEDIUM_CLONE_DATABASE_PASSWORD'] %>
