default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: '2156'

development:
  <<: *default
  host: localhost
  username: postgres
  encoding: unicode
  password: '2156'
  database: my_medium_clone_development

test:
  <<: *default
  database: my_medium_clone_test

production:
  <<: *default
  database: medium_production
  username: my_medium_clone
  password: <%= ENV['MEDIUM_DATABASE_PASSWORD'] %>
